### ISSUE TITLE
HTTPS support is missing

### ISSUE THREAD

**Issue by janisozaur** [xonsh/xonsh.github.io#3]
http://xon.sh/ doesn't redirect to https://xon.sh/ and connecting manually to https://xon.sh/ yields an invalid certificate error.

**Comment by scopatz** [comment]
Hey! Thanks for pointing this out!

**Comment by scopatz** [comment]
I believe that this might be something that @Carreau needs to address

**Comment by Carreau** [comment]
Is there repositories hosted at `xonsh.github.io/<repo_name>`, because the way to do that is to set a cname to redirect from `xonsh.github.io` to `xon.sh`, and that will break any sub-repository of the xonsh org that expose a gh pages.

The other possibility is to use something line https://www.netlify.com/ as a CDN.

Up to you. 

BTW if one of you make an account on https://www.ovh.com/ I can try to figure out how to give you technical access.

**Comment by Carreau** [comment]
hummm it's weird xonsh-docs already use the CNAME... So it should work out of the box.

**Comment by Carreau** [comment]
According to https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ `A` records should be updated as said in https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider, which should be done with a TTL of 900 so DNS should take a couple of hours to propagate, then GitHub will likely automatically setup the cert.

**Comment by Carreau** [comment]
Ok, so on top of updating the A records and having DNS to propagate I had to deactivate and reactivate custom domains for xonsh-docs. That is to say go to the repo settings, remove custom domain, and re-add. In a clean Chrome session it works(tm), but people having already visited the page may be victim of aggressive caching. So it may take some time to take effect.
<img width="1546" alt="screen shot 2018-08-09 at 11 56 35" src="https://user-images.githubusercontent.com/335567/43919704-96e3c55a-9bcb-11e8-8dd0-109337aabd72.png">

**Comment by scopatz** [comment]
Sweet! Thank you so much for doing this @Carreau! It definitely works for me now. @janisozaur - would youmind checking it on your end, please?

**Comment by janisozaur** [comment]
Definitely works! Many thanks.
